export const FETCH_SEARCH_RESULT_SAGA = 'FETCH_SEARCH_RESULT_SAGA';
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';

export const SINGLE_BOOK_SAGA ='SINGLE_BOOK_SAGA';
export const SINGLE_BOOK = 'SINGLE_BOOK';

export const GET_BOOKS_GENERAL_LIST_SAGA = 'GET_BOOKS_GENERAL_LIST_SAGA';
export const GET_BOOKS_GENERAL_LIST = 'GET_BOOKS_GENERAL_LIST';

export const FAVORITE_BOOKS_LIST = 'FAVORITE_BOOKS_LIST';